# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'prempool'

stages:

# ---------------- CLEAN ----------------
- stage: Clean_up
  displayName: Cleaning the workspace
  condition: always()
  jobs:
  - job: cleanup
    workspace:
      clean: all
    steps:
    - script: echo "Workspace cleaned"

# ---------------- BUILD ----------------
- stage: Build
  displayName: Build Frontend
  dependsOn: Clean_up
  jobs:
  - job: build
    steps:

    - checkout: self
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: '11.x'
      displayName: 'Install Node.js'

    - script: |
        node -v
        npm -v
      displayName: "Check versions"

    - script: |
        cd frontend
        npm install --legacy-peer-deps
      displayName: 'Install dependencies'

    - script: |
        cd frontend
        npm run build
      displayName: 'Build React App'

    # ---------------- ARTIFACT PREP ----------------
    - script: |
        mkdir -p artifact
        cp -r frontend/build artifact/
      displayName: "Prepare artifact folder"

    # ---------------- PUBLISH ARTIFACT ----------------
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'artifact'
        ArtifactName: 'react-build'
        publishLocation: 'Container'
      displayName: "Publish Build Artifact"