# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'prempool'
  demands:
    - terraform
parameters:
  - name: SUB_ID
    displayName: 'Azure Subscription'
    type: string


variables:
  TF_WORKING_DIR: terraform

stages:


- stage: Terraform_Plan
  displayName: Terraform Plan
  
  jobs:
  - job: plan
    displayName: Run Terraform Plan

    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: ${{ parameters.SUB_ID }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Checking Azure login..."
          az account show

          echo "Initializing Terraform..."
          terraform init -reconfigure

          echo "Running Terraform Plan..."
          terraform plan -out=tfplan

          echo "Showing Plan..."
          terraform show tfplan
        workingDirectory: $(TF_WORKING_DIR)
      displayName: Terraform Plan

    - script: |
        terraform show -no-color tfplan > plan.txt
      workingDirectory: $(TF_WORKING_DIR)
      displayName: Save Plan Output

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(TF_WORKING_DIR)/tfplan
        artifact: tfplan

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(TF_WORKING_DIR)/plan.txt
        artifact: plan-output


- stage: Terraform_Apply
  displayName: Terraform Apply
  dependsOn: Terraform_Plan
  condition: succeeded()

  jobs:
  - deployment: apply
    displayName: Apply Terraform
    environment: terraform-approval   
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: tfplan
              path: $(TF_WORKING_DIR)

          - task: AzureCLI@2
            inputs:
              azureSubscription: ${{ parameters.SUB_ID }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Initializing Terraform..."
                terraform init -reconfigure

                echo "Applying Terraform..."
                terraform apply -auto-approve tfplan
              workingDirectory: $(TF_WORKING_DIR)
            displayName: Terraform Apply
