apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: greybash/e-commerce:backend
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          value: "mongodb://admin:admin123@mongodb:27017/ecommerce?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000